### ISSUE TITLE
No 2k resolution option - given that NVidia recently upgraded the "founders"tier to 2k

### ISSUE THREAD

**Issue by MirceaMx** [AstralVixen/GeForce-Infinity#7]
So this solutin works very well. The best I've tryed BUT no 2k option (since NVidia upgraded even "founders" to 2k resolution) and my laptop fans keep spinning when I stream a game. Is hardware accelerated AV1 decoding present?

**Comment by AstralVixen** [comment]
Hello! App resolution settings will are planned with the next update as for streamed game resolution - That was already something mentioned in the discussions page and I have not made much progress on that yet as school and projects which bring me at least a little money take priority. 

As for the hardware accelerated AV1 decoding thing I'm a bit ashamed to admit but I do not know what that is, and if it's possible but I'll look into that too but please keep in mind ultimately this is just an electron app which is using the web version of geforce now.

**Comment by MirceaMx** [comment]
AV1 is a video codec supported by Intel from 11 gen+ and AMD from Ryzen 6000+ (witch is what I have)  . Since it's hardware supported and is very efficient while offering image quality superior to X264/x265 (both codecs) the CPU's that hardware support it run it without spinning fans or CPU usage and such. NVidia was using x264 and went straight for AV1 as its very efficient. Since Linux in general has an issue with hardware acceleration, I doubt you can pull it off (but on Windows it works) .
Still given that I've tried similar "unofficial" solutions it the past - Yours works best so congratulations!!! Hope you implement the resolutions soon

**Comment by AstralVixen** [comment]
Ah thanks for explaining but yeah I very highly doubt I could pull it off lol. Also thank you and next update I'll try to do around after I release a paid game I'm working on so like 1-2 months
